unique: unique.c unsorted.c
	gcc -o unique unique.c unsorted.c

bincount: bincount.c unsorted.c
	gcc -o bincount bincount.c unsorted.c

parity: parity.c unsorted.c
	gcc -o parity parity.c unsorted.c

uniquesorted: unique.c sorted.c
	gcc -o uniquesorted unique.c sorted.c

bincountsorted: bincount.c sorted.c
	gcc -o bincountsorted bincount.c sorted.c

paritysorted: parity.c sorted.c
	gcc -o paritysorted parity.c sorted.c

